/**
 * KB Overrides page.
 *
 * Surfaces the existing `kb_service_overrides` CRUD (scan_recommender's
 * /kb/services* + the BFF kb.py proxy + the api/kb.ts hooks have all
 * been shipped for a while) so operators can edit per-service KB entries
 * directly from the dashboard without dropping into psql or hand-editing
 * service_tools.yaml.
 *
 * ⚠ kb_service_overrides has NO engagement_id column -- overrides are
 * global across this installation.  The banner makes that explicit so a
 * pentester editing for "engagement A" doesn't accidentally affect
 * everyone else's auto-recs.  Engagement-scoping is deferred to a later
 * PR (requires schema + uniqueness-constraint changes).
 */

import { useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import InfoTip from '@/components/InfoTip'
import { AlertTriangle, BookOpen, Edit, RotateCcw, X, Plus, Loader2 } from 'lucide-react'
import {
  useKBServices,
  useKBService,
  useUpsertKBService,
  useDeleteKBOverride,
  type KBTool,
  type KBMsfModule,
} from '@/api/kb'

type Source = 'yaml' | 'override' | 'both'

const SOURCE_BADGE: Record<Source, string> = {
  yaml:     'bg-blue-500/15 text-blue-400 border-blue-500/30',
  both:     'bg-amber-500/15 text-amber-400 border-amber-500/30',
  override: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
}
const SOURCE_LABEL: Record<Source, string> = {
  yaml: 'YAML (default)',
  both: 'YAML + override',
  override: 'Override only',
}

export default function KbOverrides() {
  const { data, isLoading, error } = useKBServices()
  const [editing, setEditing] = useState<string | null>(null)
  const [filter, setFilter] = useState('')
  const deleteMutation = useDeleteKBOverride()

  const services = data?.services ?? []
  const filtered = filter
    ? services.filter(s => s.name.toLowerCase().includes(filter.toLowerCase()))
    : services

  return (
    <div className="p-4 space-y-3">
      <div className="flex items-center gap-2">
        <BookOpen className="h-4 w-4 text-blue-400" />
        <h2 className="text-base font-semibold">KB Service Overrides</h2>
        <InfoTip side="bottom" text={
          <>
            Two ways to steer which tools the recommender suggests for a service:
            <br /><br />
            <b>Overrides</b> (this page) <i>replace</i> a service’s whole tool / metasploit /
            nuclei-tag list — submit the full list you want.
            <br /><br />
            <b>Feedback policies</b> are surgical and layer on top — <code>suppress</code> a
            tool (e.g. metasploit <code>*robots_txt</code>), <code>add_tool</code> a
            lightweight one (e.g. <code>curl …/robots.txt</code>), or <code>add_overlap</code>
            to mark tools redundant. Both apply live, no rebuild.
          </>
        } />
        <span className="text-xs text-muted-foreground">
          {data ? `${data.count} services` : ''}
        </span>
      </div>

      {/* Global-scope warning banner -- prevents the "I edited this for
          my engagement only" misconception. */}
      <div className="flex items-start gap-2 text-xs border border-amber-500/30 bg-amber-500/5 rounded p-2">
        <AlertTriangle className="h-3.5 w-3.5 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <span className="font-medium text-amber-400">Overrides are global.</span>{' '}
          <span className="text-muted-foreground">
            Changes apply to this installation, not the active engagement.
            Recommendations generated by future scans against any engagement
            will use the edited mappings.
          </span>
        </div>
      </div>

      <input
        value={filter}
        onChange={e => setFilter(e.target.value)}
        placeholder="Filter services…"
        className="w-full max-w-sm h-7 px-2 text-xs rounded border border-border bg-background text-foreground outline-none focus:border-primary"
      />

      {isLoading && (
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Loader2 className="h-3 w-3 animate-spin" />
          Loading services…
        </div>
      )}
      {error && (
        <div className="text-xs text-red-400 border border-red-500/30 bg-red-500/5 rounded p-2">
          Failed to load KB services: {String(error)}
        </div>
      )}

      {data && (
        <div className="border border-border rounded-lg overflow-hidden">
          <table className="w-full text-xs">
            <thead className="bg-muted/40 text-muted-foreground">
              <tr>
                <th className="text-left px-3 py-1.5 font-medium">Service</th>
                <th className="text-left px-3 py-1.5 font-medium">Source</th>
                <th className="text-left px-3 py-1.5 font-medium">Ports</th>
                <th className="text-right px-3 py-1.5 font-medium">Tools</th>
                <th className="text-right px-3 py-1.5 font-medium">MSF</th>
                <th className="text-left px-3 py-1.5 font-medium">Nuclei tags</th>
                <th className="text-right px-3 py-1.5 font-medium w-44">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((svc) => (
                <tr key={svc.name} className="border-t border-border/30 hover:bg-muted/20">
                  <td className="px-3 py-1.5 font-mono font-medium">{svc.name}</td>
                  <td className="px-3 py-1.5">
                    <span className={`px-1.5 py-0.5 rounded text-[10px] border ${SOURCE_BADGE[svc.source as Source] || ''}`}>
                      {SOURCE_LABEL[svc.source as Source] || svc.source}
                    </span>
                  </td>
                  <td className="px-3 py-1.5 font-mono text-[10px] text-muted-foreground">
                    {svc.ports?.join(', ') || '—'}
                  </td>
                  <td className="px-3 py-1.5 text-right">{svc.tool_count}</td>
                  <td className="px-3 py-1.5 text-right">{svc.msf_count}</td>
                  <td className="px-3 py-1.5 text-[10px] text-muted-foreground truncate max-w-xs">
                    {svc.nuclei_tags?.join(', ') || '—'}
                  </td>
                  <td className="px-3 py-1.5 text-right space-x-1">
                    <button
                      type="button"
                      onClick={() => setEditing(svc.name)}
                      className="px-2 py-0.5 text-[10px] rounded border border-border bg-muted/40 hover:bg-muted inline-flex items-center gap-1"
                    >
                      <Edit className="h-3 w-3" /> Edit
                    </button>
                    {svc.source !== 'yaml' && (
                      <button
                        type="button"
                        onClick={() => {
                          if (!window.confirm(
                            `Revert override for "${svc.name}"?\n\n` +
                            (svc.source === 'override'
                              ? 'This service has NO YAML default -- reverting will remove it entirely from the KB.'
                              : 'The YAML default for this service will be restored.')
                          )) return
                          deleteMutation.mutate(svc.name)
                        }}
                        disabled={deleteMutation.isPending}
                        className="px-2 py-0.5 text-[10px] rounded border border-border text-muted-foreground hover:text-foreground inline-flex items-center gap-1 disabled:opacity-50"
                        title="Delete override and revert to YAML defaults"
                      >
                        <RotateCcw className="h-3 w-3" /> Revert
                      </button>
                    )}
                  </td>
                </tr>
              ))}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-3 py-6 text-center text-muted-foreground italic">
                    {filter ? 'No services match the filter.' : 'No KB services loaded.'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      {editing && (
        <KbServiceEditModal name={editing} onClose={() => setEditing(null)} />
      )}
    </div>
  )
}

// ---- Edit modal ----

function KbServiceEditModal({ name, onClose }: { name: string; onClose: () => void }) {
  const { data, isLoading } = useKBService(name)
  const upsert = useUpsertKBService()
  // Local working copy of the editable fields; commits to the DB override
  // on Save.  Keeping it local means cancel-without-save is just `onClose()`.
  const [description, setDescription] = useState('')
  const [portsText, setPortsText] = useState('')
  const [tools, setTools] = useState<KBTool[]>([])
  const [msf, setMsf] = useState<KBMsfModule[]>([])
  const [nucleiTagsText, setNucleiTagsText] = useState('')
  const [commonVulnsText, setCommonVulnsText] = useState('')
  const [hydrated, setHydrated] = useState(false)

  // Hydrate once when the fetch lands.  Don't depend on `data` directly
  // in a useEffect (avoids re-resetting if the user mid-edits while the
  // background refetch fires).
  if (!hydrated && data) {
    setHydrated(true)
    setDescription(data.data.description || '')
    setPortsText((data.data.ports || []).join(', '))
    setTools(data.data.tools || [])
    setMsf(data.data.metasploit || [])
    setNucleiTagsText((data.data.nuclei_tags || []).join(', '))
    setCommonVulnsText((data.data.common_vulns || []).join('\n'))
  }

  const parseCsvNumbers = (s: string): number[] =>
    s.split(',').map(p => p.trim()).filter(Boolean).map(Number).filter(n => !Number.isNaN(n))
  const parseCsv = (s: string): string[] =>
    s.split(',').map(p => p.trim()).filter(Boolean)
  const parseLines = (s: string): string[] =>
    s.split('\n').map(p => p.trim()).filter(Boolean)

  const handleSave = () => {
    upsert.mutate(
      {
        name,
        data: {
          description: description.trim() || undefined,
          ports: parseCsvNumbers(portsText),
          tools: tools.filter(t => t.name?.trim()),
          metasploit: msf.filter(m => m.module?.trim()),
          nuclei_tags: parseCsv(nucleiTagsText),
          common_vulns: parseLines(commonVulnsText),
        },
      },
      { onSuccess: () => onClose() },
    )
  }

  const addTool = () => setTools([...tools, { name: '', purpose: '', command: '' }])
  const updateTool = (i: number, patch: Partial<KBTool>) =>
    setTools(tools.map((t, idx) => idx === i ? { ...t, ...patch } : t))
  const removeTool = (i: number) =>
    setTools(tools.filter((_, idx) => idx !== i))

  const addMsf = () => setMsf([...msf, { module: '', purpose: '' }])
  const updateMsf = (i: number, patch: Partial<KBMsfModule>) =>
    setMsf(msf.map((m, idx) => idx === i ? { ...m, ...patch } : m))
  const removeMsf = (i: number) =>
    setMsf(msf.filter((_, idx) => idx !== i))

  return (
    <Dialog.Root open onOpenChange={(open) => { if (!open) onClose() }}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/50 z-[70]" />
        <Dialog.Content className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[92vw] max-w-[760px] max-h-[88vh] overflow-y-auto bg-card border border-border rounded-lg shadow-2xl z-[80] p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Edit className="h-4 w-4 text-blue-400" />
              <Dialog.Title className="text-sm font-semibold">Edit KB Service: {name}</Dialog.Title>
              {data && (
                <span className={`px-1.5 py-0.5 rounded text-[10px] border ${SOURCE_BADGE[data.source as Source] || ''}`}>
                  {SOURCE_LABEL[data.source as Source] || data.source}
                </span>
              )}
            </div>
            <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
              <X className="h-4 w-4" />
            </button>
          </div>

          {isLoading && (
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Loader2 className="h-3 w-3 animate-spin" />
              Loading service…
            </div>
          )}

          {data && (
            <div className="space-y-3 text-xs">
              <div>
                <label className="block font-medium mb-1">Description</label>
                <textarea
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  rows={2}
                  className="w-full rounded border border-border bg-background text-foreground p-1.5 outline-none focus:border-primary text-xs"
                />
              </div>

              <div>
                <label className="block font-medium mb-1">Ports (comma-separated)</label>
                <input
                  value={portsText}
                  onChange={e => setPortsText(e.target.value)}
                  placeholder="22, 2222"
                  className="w-full h-7 px-2 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-xs"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="font-medium">Tools ({tools.length})</label>
                  <button
                    type="button"
                    onClick={addTool}
                    className="px-2 py-0.5 text-[10px] rounded border border-border bg-muted/40 hover:bg-muted inline-flex items-center gap-1"
                  >
                    <Plus className="h-3 w-3" /> Add tool
                  </button>
                </div>
                <div className="space-y-1.5">
                  {tools.map((t, i) => (
                    <div key={i} className="border border-border rounded p-1.5 space-y-1">
                      <div className="flex gap-1.5">
                        <input
                          value={t.name || ''}
                          onChange={e => updateTool(i, { name: e.target.value })}
                          placeholder="tool name (e.g. hydra)"
                          className="flex-1 h-6 px-1.5 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-[11px] font-mono"
                        />
                        <input
                          value={t.purpose || ''}
                          onChange={e => updateTool(i, { purpose: e.target.value })}
                          placeholder="purpose (one line)"
                          className="flex-[2] h-6 px-1.5 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-[11px]"
                        />
                        <button
                          type="button"
                          onClick={() => removeTool(i)}
                          className="h-6 w-6 rounded border border-border text-muted-foreground hover:text-red-400 inline-flex items-center justify-center"
                          title="Remove tool"
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </div>
                      <input
                        value={t.command || ''}
                        onChange={e => updateTool(i, { command: e.target.value })}
                        placeholder="example command (optional)"
                        className="w-full h-6 px-1.5 rounded border border-border bg-background text-muted-foreground outline-none focus:border-primary text-[10px] font-mono"
                      />
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="font-medium">Metasploit modules ({msf.length})</label>
                  <button
                    type="button"
                    onClick={addMsf}
                    className="px-2 py-0.5 text-[10px] rounded border border-border bg-muted/40 hover:bg-muted inline-flex items-center gap-1"
                  >
                    <Plus className="h-3 w-3" /> Add module
                  </button>
                </div>
                <div className="space-y-1">
                  {msf.map((m, i) => (
                    <div key={i} className="flex gap-1.5">
                      <input
                        value={m.module || ''}
                        onChange={e => updateMsf(i, { module: e.target.value })}
                        placeholder="module path (e.g. auxiliary/scanner/ssh/ssh_login)"
                        className="flex-[3] h-6 px-1.5 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-[11px] font-mono"
                      />
                      <input
                        value={m.purpose || ''}
                        onChange={e => updateMsf(i, { purpose: e.target.value })}
                        placeholder="purpose"
                        className="flex-[2] h-6 px-1.5 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-[11px]"
                      />
                      <button
                        type="button"
                        onClick={() => removeMsf(i)}
                        className="h-6 w-6 rounded border border-border text-muted-foreground hover:text-red-400 inline-flex items-center justify-center"
                        title="Remove module"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <label className="block font-medium mb-1">Nuclei tags (comma-separated)</label>
                <input
                  value={nucleiTagsText}
                  onChange={e => setNucleiTagsText(e.target.value)}
                  placeholder="ssh, exposure, default-login"
                  className="w-full h-7 px-2 rounded border border-border bg-background text-foreground outline-none focus:border-primary text-xs"
                />
              </div>

              <div>
                <label className="block font-medium mb-1">Common vulns (one per line)</label>
                <textarea
                  value={commonVulnsText}
                  onChange={e => setCommonVulnsText(e.target.value)}
                  rows={3}
                  placeholder="Weak credentials&#10;CVE-2018-15473 user enumeration"
                  className="w-full rounded border border-border bg-background text-foreground p-1.5 outline-none focus:border-primary text-xs font-mono"
                />
              </div>

              {upsert.isError && (
                <div className="text-xs text-red-400 border border-red-500/30 bg-red-500/5 rounded p-2">
                  Save failed: {String(upsert.error)}
                </div>
              )}

              <div className="flex justify-end gap-2 pt-2 border-t border-border/50">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-3 py-1 text-xs rounded border border-border hover:bg-muted/40"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleSave}
                  disabled={upsert.isPending}
                  className="px-3 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 inline-flex items-center gap-1.5 disabled:opacity-50"
                >
                  {upsert.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : null}
                  Save override
                </button>
              </div>
            </div>
          )}
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}
