"""The coverage report must count PROACTIVE generators, not just the map.

WHY THIS EXISTS
---------------
`app/rag-api/wstg_coverage.py` derived `has_generator` from
`knowledge/wstg_map.yaml` alone. That map is FINDING-DRIVEN: an entry fires when a
scanner reports something matching. But the surface phase in
`autogen_agents/langgraph_engine.py` also emits tests unprompted — per web service
and per crawled parameter — and those carry no map entry.

So the report under-counted. `WSTG-ATHN-06` (browser cache weakness) has been
probed on every web service since the Tier-2 work, and was still being listed as
an *automatable gap* — work that looks outstanding and is already done. That is
the expensive direction to be wrong in: it sends someone to build a thing twice.

The two live in different containers (langgraph_engine in autogen-agents,
wstg_coverage in rag-api) and rag-api cannot import across, so the set is
duplicated by necessity. CLAUDE.md's rule for that case is an agreement test
pinning both sides — this is it.

Sabotage check: add a new "WSTG-XXXX-99" _svc_test to langgraph_engine without
declaring it -> test_proactive_ids_are_declared RED.
"""
import ast
import os
import re

import pytest

yaml = pytest.importorskip("yaml")

REPO = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))
COVERAGE = os.path.join(REPO, "app", "rag-api", "wstg_coverage.py")
ENGINE = os.path.join(REPO, "autogen_agents", "langgraph_engine.py")
MAP = os.path.join(REPO, "knowledge", "wstg_map.yaml")

_ID_RE = re.compile(r"WSTG-[A-Z]+-\d+")


def _declared_proactive():
    """PROACTIVE_WSTG_IDS read via ast — no import, so this runs on a bare checkout."""
    if not os.path.exists(COVERAGE):
        pytest.skip("wstg_coverage.py not present")
    tree = ast.parse(open(COVERAGE, encoding="utf-8").read())
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and getattr(node.targets[0], "id", "") == "PROACTIVE_WSTG_IDS"):
            return set(ast.literal_eval(node.value))
    raise AssertionError("PROACTIVE_WSTG_IDS not found — this guard would pass vacuously")


def _engine_ids():
    """Every WSTG id the surface generators name."""
    if not os.path.exists(ENGINE):
        pytest.skip("langgraph_engine.py not present")
    src = open(ENGINE, encoding="utf-8").read()
    # Only string literals, so a comment mentioning an id does not count.
    ids = set()
    for node in ast.walk(ast.parse(src)):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            ids.update(_ID_RE.findall(node.value))
    assert ids, "no WSTG ids found in langgraph_engine.py — guard would pass vacuously"
    return ids


def _map_ids():
    if not os.path.exists(MAP):
        pytest.skip("wstg_map.yaml not present")
    with open(MAP, encoding="utf-8") as fh:
        entries = (yaml.safe_load(fh) or {}).get("entries") or []
    ids = set()
    for e in entries:
        w = e.get("wstg_id")
        for x in (w if isinstance(w, list) else [w]):
            ids.update(_ID_RE.findall(str(x)))
    assert ids, "no ids parsed from wstg_map.yaml"
    return ids


def test_proactive_ids_are_declared():
    """Any id the engine generates that the MAP does not carry must be declared,
    or the coverage report reports it as an outstanding gap forever."""
    undeclared = sorted(_engine_ids() - _map_ids() - _declared_proactive())
    assert not undeclared, (
        "these WSTG ids are generated by langgraph_engine.py but appear in neither "
        "wstg_map.yaml nor PROACTIVE_WSTG_IDS, so the coverage report counts them "
        f"as automatable gaps although the test already runs: {undeclared}"
    )


def test_no_stale_proactive_declarations():
    """A declared id the engine no longer generates inflates the score."""
    engine = _engine_ids()
    stale = sorted(i for i in _declared_proactive() if i not in engine)
    assert not stale, (
        "these ids are declared in PROACTIVE_WSTG_IDS but langgraph_engine.py no "
        f"longer generates them — coverage would be overstated: {stale}"
    )


def test_declared_ids_are_real_catalog_entries():
    """A typo would silently add nothing."""
    tree = ast.parse(open(COVERAGE, encoding="utf-8").read())
    catalog = None
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and getattr(node.targets[0], "id", "") == "CATALOG"):
            catalog = set(ast.literal_eval(node.value).keys())
    assert catalog and len(catalog) > 90, "CATALOG not parsed — guard would be vacuous"
    bogus = sorted(i for i in _declared_proactive() if i not in catalog)
    assert not bogus, f"declared ids that are not in the WSTG catalog: {bogus}"


def test_athn06_is_counted():
    """The concrete regression: it is probed by _svc_test('cache_check', ...)."""
    assert "WSTG-ATHN-06" in _engine_ids(), \
        "langgraph_engine no longer probes ATHN-06 — remove it from PROACTIVE_WSTG_IDS"
    assert "WSTG-ATHN-06" in (_map_ids() | _declared_proactive()), \
        "ATHN-06 is generated but counted by neither source"
