openapi: 3.0.3
info:
  title: Web Scanner
  version: "0.0.1"
servers:
  - url: http://localhost:7080/web
  - url: https://localhost:7443/web
tags:
  - name: Health
paths:
  /health:
    get:
      tags: [Health]
      operationId: webScannerHealth
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              example: { status: "ok" }
