import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from './client'
import { POLL } from '@/lib/polling'

export interface SecurityTest {
  id: string
  name: string
  description?: string | null
  tier: 'safe' | 'impactful'
  category?: string | null
  target_ip?: string | null
  target_host?: string | null
  target_port?: number | null
  target_service?: string | null
  command?: string | null
  tool?: string | null
  assertion?: Record<string, unknown> | null
  pending_exploit_id?: string | null
  created_by_session?: string | null
  engagement_id?: string | null
  enabled: boolean
  last_run_at?: string | null
  last_run_status?: 'pass' | 'fail' | 'error' | 'skipped' | null
  run_count: number
  created_at?: string
}

export interface SecurityTestRun {
  id: string
  test_id: string
  ran_at?: string
  completed_at?: string | null
  duration_ms?: number | null
  status: 'pass' | 'fail' | 'error' | 'skipped'
  lane: 'safe' | 'impactful'
  command_run?: string | null
  exit_code?: number | null
  result_summary?: string | null
  assertion_eval?: Record<string, unknown> | null
  tool_execution_id?: string | null
  exploit_result_id?: string | null
  output?: string | null
}

/** Tests generated by one agent session. */
export function useSessionSecurityTests(sessionId: string | undefined) {
  return useQuery({
    queryKey: ['security-tests', 'session', sessionId],
    queryFn: () =>
      apiFetch<{ tests: SecurityTest[] }>(`/agent-sessions/${sessionId}/security-tests`),
    enabled: !!sessionId,
    refetchInterval: POLL.FAST,
    placeholderData: (prev: { tests: SecurityTest[] } | undefined) => prev,
    retry: 1,
  })
}

export function useSecurityTestRuns(testId: string | undefined) {
  return useQuery({
    queryKey: ['security-test-runs', testId],
    queryFn: () => apiFetch<{ runs: SecurityTestRun[] }>(`/security-tests/${testId}/runs`),
    enabled: !!testId,
    refetchInterval: POLL.FAST,
    placeholderData: (prev: { runs: SecurityTestRun[] } | undefined) => prev,
    retry: 1,
  })
}

/** Re-run a stored test. Safe tests execute immediately and append a run;
 *  impactful tests return { requires_approval: true } and run nothing until the
 *  operator approves through the exploit-approval banner. */
export function useRunSecurityTest(sessionId?: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (vars: { id: string; proxy?: string }) =>
      apiFetch<{
        status?: string
        run_id?: string
        requires_approval?: boolean
        pending_exploit_id?: string
      }>(`/security-tests/${vars.id}/run`, {
        method: 'POST',
        body: JSON.stringify({
          proxy: vars.proxy,
          triggered_by_session: sessionId,
        }),
      }),
    onSuccess: (_d, vars) => {
      qc.invalidateQueries({ queryKey: ['security-test-runs', vars.id] })
      if (sessionId)
        qc.invalidateQueries({ queryKey: ['security-tests', 'session', sessionId] })
    },
  })
}

export function useToggleSecurityTest(sessionId?: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (vars: { id: string; enabled: boolean }) =>
      apiFetch<{ id: string }>(`/security-tests/${vars.id}`, {
        method: 'PATCH',
        body: JSON.stringify({ enabled: vars.enabled }),
      }),
    onSuccess: () => {
      if (sessionId)
        qc.invalidateQueries({ queryKey: ['security-tests', 'session', sessionId] })
    },
  })
}
