#!/usr/bin/env python3
"""Generate knowledge/seed/gtfobins.yaml from a GTFOBins clone.

GTFOBins (https://gtfobins.github.io, part of the lolol.farm LOL directory) is a
library of Living-Off-the-Land techniques per Unix binary — how to get a shell,
read/write files, or escalate (sudo/suid/capabilities) with a binary already on
the box. Ingested as retrievable knowledge (doc_kind='gtfobins') so the tool
recommendations surface "if `find` is available, here's how to shell/escalate"
during enumeration.

    git clone --depth 1 https://github.com/GTFOBins/GTFOBins.github.io.git /tmp/gtfobins
    python3 scripts/gtfobins-to-seed.py /tmp/gtfobins --out knowledge/seed/gtfobins.yaml
    ./scripts/import-knowledge.sh --file knowledge/seed/gtfobins.yaml

Licence: GTFOBins is MIT. Attribution retained per entry.
"""
import argparse
import os
import sys

import yaml

# Functions most useful to an enumerating agent, in priority order.
_ORDER = ["shell", "reverse-shell", "bind-shell", "command", "file-read",
          "file-write", "file-upload", "file-download", "sudo", "suid",
          "capabilities", "limited-suid", "library-load", "non-interactive-reverse-shell"]


def _fmt_entry(name, data):
    funcs = (data or {}).get("functions") or {}
    if not funcs:
        return None
    lines = [f"## GTFOBins: {name}",
             f"Living-off-the-land techniques for the `{name}` binary (GTFOBins, MIT).",
             ""]
    keys = [k for k in _ORDER if k in funcs] + [k for k in funcs if k not in _ORDER]
    for fn in keys:
        entries = funcs.get(fn) or []
        if not isinstance(entries, list):
            continue
        lines.append(f"### {fn}")
        for e in entries[:3]:
            code = (e.get("code") or "").strip() if isinstance(e, dict) else str(e)
            if code:
                lines.append("```")
                lines.append(code)
                lines.append("```")
            ctx = (e.get("contexts") if isinstance(e, dict) else None) or {}
            if isinstance(ctx, dict) and ctx:
                lines.append("_contexts: " + ", ".join(sorted(str(k) for k in ctx)) + "_")
            cm = (e.get("comment") if isinstance(e, dict) else "") or ""
            if cm.strip():
                lines.append(cm.strip()[:300])
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build(clone):
    base = os.path.join(clone, "_gtfobins")
    if not os.path.isdir(base):
        sys.exit(f"not a GTFOBins clone (missing {base})")
    out = []
    for fn in sorted(os.listdir(base)):
        path = os.path.join(base, fn)
        if not os.path.isfile(path):
            continue
        try:
            raw = open(path, encoding="utf-8").read()
            data = yaml.safe_load(raw.split("---", 2)[1]) if raw.startswith("---") else yaml.safe_load(raw)
        except Exception:
            continue
        content = _fmt_entry(fn, data)
        if content:
            out.append({"title": f"GTFOBins {fn}", "tech": "lolbin",
                        "content": content})
    return out


def emit(entries, outp):
    def block(s, ind):
        pad = " " * ind
        return "\n".join(pad + ln if ln else "" for ln in s.split("\n"))
    L = ["# GTFOBins -> Living-off-the-land technique knowledge (per Unix binary).",
         "# GENERATED by scripts/gtfobins-to-seed.py from a clone of",
         "# https://github.com/GTFOBins/GTFOBins.github.io (MIT). Regenerate; do not hand-edit.",
         "#",
         "# Import: ./scripts/import-knowledge.sh --file knowledge/seed/gtfobins.yaml",
         f"# {len(entries)} binaries; service=linux, doc_kind=gtfobins.", "",
         "service_docs:"]
    for e in entries:
        t = e["title"].replace('"', '\\"')
        L.append(f'- title: "{t}"')
        L.append("  service: linux")
        L.append("  tech: lolbin")
        L.append("  doc_kind: gtfobins")
        L.append("  content: |-")
        L.append(block(e["content"].rstrip("\n"), 4))
    open(outp, "w", encoding="utf-8").write("\n".join(L) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("clone"); ap.add_argument("--out", default="knowledge/seed/gtfobins.yaml")
    a = ap.parse_args()
    entries = build(a.clone)
    if not entries:
        sys.exit("no GTFOBins entries found")
    emit(entries, a.out)
    print(f"wrote {a.out}: {len(entries)} GTFOBins binaries")


if __name__ == "__main__":
    main()
