#!/usr/bin/env bash
#
# refresh-tool-catalogs.sh — snapshot what the scanners can actually run.
#
# Writes knowledge/tool_catalogs.json: the real nmap scripts, nuclei templates
# and metasploit modules present in the running containers. The recommendation
# validator checks LLM- and rule-generated invocations against this, so a
# suggestion that cannot execute is rejected before it is persisted or run.
#
# The motivating case was live: the model recommended `smb Vuln-MS17-010` —
# capital V, space instead of a hyphen — which is not an nmap script. It would
# have been dispatched and failed at the scanner.
#
# The catalogs live in three different containers, so this materialises them
# into knowledge/ (already bind-mounted read-only into scan-recommender) rather
# than having the validator reach across containers at request time.
#
# Re-run after upgrading a scanner image or updating nuclei templates.
#
# Usage:
#   ./scripts/refresh-tool-catalogs.sh
#   ./scripts/refresh-tool-catalogs.sh --out knowledge/tool_catalogs.json
#
# Prereqs: docker, jq. Containers kali-listener / nuclei-runner / metasploit
# must be running; each source is optional and simply reports 0 if absent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

OUT="knowledge/tool_catalogs.json"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out|-o)  OUT="${2:-}"; shift 2 ;;
        --help|-h) sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required." >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Each extractor prints one entry per line and must never fail the run: a
# missing container degrades that catalog to empty, and the validator treats an
# empty catalog as "cannot verify" rather than "everything is invalid".
extract() {   # container, description, shell command
    local container="$1" what="$2" cmd="$3"
    if docker exec "$container" sh -c "$cmd" 2>/dev/null | sed '/^$/d' | sort -u > "$TMP/$what"; then
        :
    else
        : > "$TMP/$what"
    fi
    printf "  %-22s %6d  (%s)\n" "$what" "$(wc -l < "$TMP/$what" | tr -d ' ')" "$container"
}

echo "Extracting tool catalogs from running containers…"

extract kali-listener nmap_scripts \
    'ls /usr/share/nmap/scripts/*.nse 2>/dev/null | xargs -n1 basename | sed "s/\.nse$//"'

extract metasploit msf_modules \
    'find /usr/src/metasploit-framework/modules /usr/share/metasploit-framework/modules -name "*.rb" 2>/dev/null | sed "s|.*/modules/||; s|\.rb$||"'

extract nuclei-runner nuclei_templates \
    'find /opt/nuclei-templates /root/nuclei-templates -name "*.yaml" 2>/dev/null | sed "s|.*/nuclei-templates/||; s|\.yaml$||"'

# Nuclei is usually invoked by TAG rather than template id (the model emits
# "snmp,network,udp"), so the tag vocabulary has to be validated separately.
extract nuclei-runner nuclei_tags \
    'grep -rhoE "^\s{0,4}tags:\s*.*" /opt/nuclei-templates --include="*.yaml" 2>/dev/null | sed "s/.*tags:\s*//" | tr "," "\n" | tr -d "\"'"'"' " | tr "[:upper:]" "[:lower:]"'

python3 - "$TMP" "$OUT" <<'PY'
import json, os, sys, datetime
tmp, out = sys.argv[1], sys.argv[2]
def load(name):
    p = os.path.join(tmp, name)
    if not os.path.exists(p):
        return []
    with open(p) as fh:
        return sorted({ln.strip() for ln in fh if ln.strip()})
data = {
    "generated_at": datetime.datetime.now(datetime.timezone.utc)
                        .replace(microsecond=0).isoformat(),
    "note": ("Generated by scripts/refresh-tool-catalogs.sh. An EMPTY list means "
             "'catalog unavailable' — the validator skips that tool rather than "
             "rejecting everything. Re-run after upgrading a scanner image."),
    "nmap_scripts":     load("nmap_scripts"),
    "msf_modules":      load("msf_modules"),
    "nuclei_templates": load("nuclei_templates"),
    "nuclei_tags":      load("nuclei_tags"),
}
os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
with open(out, "w") as fh:
    json.dump(data, fh, indent=1, sort_keys=True)
total = sum(len(v) for k, v in data.items() if isinstance(v, list))
print(f"\nWrote {out} — {total} catalog entries")
for k, v in data.items():
    if isinstance(v, list) and not v:
        print(f"  WARNING: {k} is empty — that tool will not be validated")
PY

cat <<EOF

Next:
  Restart scan-recommender so it picks up the new catalog:
    docker compose restart scan-recommender
EOF
