#!/usr/bin/env python3
"""Generate knowledge/seed/wstg.yaml from a clone of OWASP/wstg (CC BY-SA 4.0).

The OWASP Web Security Testing Guide is the standard methodology for turning a
web finding into a concrete test. This converts each WSTG test document into a
retrievable `service_docs` entry (doc_kind='wstg') so the agent's RAG context
and the finding->WSTG guidance lookup can surface "how to test this" for a given
web finding.

GENERATED — regenerate rather than hand-editing:
    git clone --depth 1 https://github.com/OWASP/wstg.git /tmp/wstg
    python3 scripts/wstg-to-seed.py /tmp/wstg --out knowledge/seed/wstg.yaml
    ./scripts/import-knowledge.sh --file knowledge/seed/wstg.yaml

Attribution / licence: content is OWASP WSTG, CC BY-SA 4.0
(https://github.com/OWASP/wstg, https://creativecommons.org/licenses/by-sa/4.0/).
The WSTG-ID and the source path are retained on every entry as attribution.
Share-alike: derived seed text stays under CC BY-SA 4.0.
"""
import argparse
import os
import re
import sys

# Category dir -> (service is always http; tech is a coarse vuln-class slug used
# as a retrieval group). One tech per WSTG category; the precise finding->test
# keying lives in knowledge/wstg_map.yaml, not here.
CATEGORY_TECH = {
    "01-Information_Gathering": "recon",
    "02-Configuration_and_Deployment_Management_Testing": "config",
    "03-Identity_Management_Testing": "identity",
    "04-Authentication_Testing": "auth",
    "05-Authorization_Testing": "authz",
    "06-Session_Management_Testing": "session",
    "07-Input_Validation_Testing": "injection",
    "08-Testing_for_Error_Handling": "errors",
    "09-Testing_for_Weak_Cryptography": "crypto",
    "10-Business_Logic_Testing": "buslogic",
    "11-Client-side_Testing": "clientside",
    "12-API_Testing": "api",
}

ID_RE = re.compile(r"\|\s*(WSTG-[A-Z]+-[0-9]+(?:\.[0-9]+)?)\s*\|")
HOWTO_CAP = 6000  # chars; the full guide is linked, we keep the actionable head


def _section(text, header):
    """Return the body of a `## header` section (up to the next `## `)."""
    m = re.search(rf"^##\s+{re.escape(header)}\s*$", text, re.M)
    if not m:
        return ""
    start = m.end()
    nxt = re.search(r"^##\s+", text[start:], re.M)
    body = text[start:start + nxt.start()] if nxt else text[start:]
    return body.strip()


def _first_para(text):
    body = _section(text, "Summary")
    for para in body.split("\n\n"):
        p = para.strip()
        if p and not p.startswith(("|", ">", "#")):
            return p
    return body[:600].strip()


def parse_doc(path, category):
    raw = open(path, encoding="utf-8").read()
    m = ID_RE.search(raw)
    if not m:
        return None
    wstg_id = m.group(1)
    tm = re.search(r"^#\s+(.+?)\s*$", raw, re.M)
    title = tm.group(1).strip() if tm else os.path.basename(path)
    objectives = _section(raw, "Test Objectives")
    howto = _section(raw, "How to Test")
    if len(howto) > HOWTO_CAP:
        howto = howto[:HOWTO_CAP].rstrip() + "\n\n_(truncated — see the full WSTG test)_"
    summary = _first_para(raw)

    rel = os.path.relpath(path).split("wstg/")[-1]
    url = ("https://github.com/OWASP/wstg/blob/master/"
           + path.split("wstg/", 1)[-1] if "wstg/" in path else rel)

    content = [f"## {wstg_id} — {title}", "",
               f"Category: {category}  ", f"Source: OWASP WSTG ({wstg_id}) — CC BY-SA 4.0", ""]
    if summary:
        content += [summary, ""]
    if objectives:
        content += ["### Test Objectives", "", objectives, ""]
    if howto:
        content += ["### How to Test", "", howto, ""]
    return {
        "wstg_id": wstg_id,
        "title": f"{wstg_id} {title}",
        "tech": CATEGORY_TECH.get(category, "web"),
        "content": "\n".join(content).rstrip() + "\n",
    }


def build(root):
    base = os.path.join(root, "document", "4-Web_Application_Security_Testing")
    if not os.path.isdir(base):
        sys.exit(f"not a WSTG clone (missing {base})")
    entries = []
    for category in sorted(os.listdir(base)):
        cdir = os.path.join(base, category)
        if not os.path.isdir(cdir) or not re.match(r"^[0-9]", category):
            continue
        for fn in sorted(os.listdir(cdir)):
            if not fn.endswith(".md"):
                continue
            doc = parse_doc(os.path.join(cdir, fn), category)
            if doc:
                entries.append(doc)
    return entries


def emit_yaml(entries, out):
    def block(s, indent):
        pad = " " * indent
        return "\n".join(pad + ln if ln else "" for ln in s.split("\n"))

    lines = [
        "# OWASP Web Security Testing Guide (WSTG) -> Layer 4 web-testing knowledge.",
        "#",
        "# GENERATED by scripts/wstg-to-seed.py from a clone of",
        "# https://github.com/OWASP/wstg  (content: CC BY-SA 4.0). Regenerate rather",
        "# than hand-editing. The WSTG-ID is retained on every entry as attribution;",
        "# derived text stays under CC BY-SA 4.0 (share-alike).",
        "#",
        "# Import (idempotent, keyed on (service,port,tech,title)):",
        "#   ./scripts/import-knowledge.sh --file knowledge/seed/wstg.yaml",
        "#",
        f"# {len(entries)} WSTG test documents, service=http (family covers https/tls).",
        "",
        "service_docs:",
    ]
    for e in entries:
        lines.append(f"- title: {yaml_str(e['title'])}")
        lines.append("  service: http")
        lines.append(f"  tech: {e['tech']}")
        lines.append("  doc_kind: wstg")
        lines.append("  content: |-")
        lines.append(block(e["content"].rstrip("\n"), 4))
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def yaml_str(s):
    if re.search(r"[:#\[\]{}]", s) or s != s.strip():
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("clone", help="path to an OWASP/wstg clone")
    ap.add_argument("--out", default="knowledge/seed/wstg.yaml")
    a = ap.parse_args()
    entries = build(a.clone)
    if not entries:
        sys.exit("no WSTG test docs found")
    emit_yaml(entries, a.out)
    print(f"wrote {a.out}: {len(entries)} WSTG test documents")
    by = {}
    for e in entries:
        by[e["tech"]] = by.get(e["tech"], 0) + 1
    print("by tech:", dict(sorted(by.items(), key=lambda x: -x[1])))


if __name__ == "__main__":
    main()
